//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wtq.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wtq.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	// V2 WIP Discussion: https://github.com/flyingpie/windows-terminal-quake/discussions/119
        ///	// Docs: https://wtq.flyingpie.nl
        ///	&quot;$schema&quot;: &quot;wtq.schema.2.json&quot;,
        ///
        ///	&quot;Apps&quot;: [
        ///		// Example with PowerShell
        ///		{
        ///			&quot;Name&quot;: &quot;PowerShell&quot;,
        ///			&quot;HotKeys&quot;: [{ &quot;Modifiers&quot;: &quot;Control&quot;, &quot;Key&quot;: &quot;D1&quot; }],
        ///			&quot;FileName&quot;: &quot;powershell&quot;
        ///		}
        ///	],
        ///
        ///	// Hot keys that toggle the most recent app (or the first one if none has been active yet).
        ///	&quot;HotKeys&quot;: [ { &quot;Modifiers&quot;: &quot;Control&quot;, &quot;Key&quot;: &quot;Q&quot; } ]
        ///}.
        /// </summary>
        public static string wtq_example_ps {
            get {
                return ResourceManager.GetString("wtq_example_ps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	// V2 WIP Discussion: https://github.com/flyingpie/windows-terminal-quake/discussions/119
        ///	// Docs: https://wtq.flyingpie.nl
        ///	&quot;$schema&quot;: &quot;wtq.schema.2.json&quot;,
        ///
        ///	&quot;Apps&quot;: [
        ///		// Example with Windows Terminal
        ///		{
        ///			&quot;Name&quot;: &quot;Terminal&quot;,
        ///			&quot;HotKeys&quot;: [{ &quot;Modifiers&quot;: &quot;Control&quot;, &quot;Key&quot;: &quot;D1&quot; }],
        ///			&quot;FileName&quot;: &quot;wt&quot;,
        ///			&quot;ProcessName&quot;: &quot;WindowsTerminal&quot;
        ///		}
        ///	],
        ///
        ///	// Hot keys that toggle the most recent app (or the first one if none has been active yet).
        ///	&quot;HotKeys&quot;: [ { &quot;Modifiers&quot;: &quot;Control&quot;, &quot;Key&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string wtq_example_wt {
            get {
                return ResourceManager.GetString("wtq_example_wt", resourceCulture);
            }
        }
    }
}
