trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: Cake@2
  inputs:
    script: 'build.cake'
    target: 'Default'
    verbosity: 'Verbose'
    arguments: '--output="$(Build.StagingDirectory)"'
