global using Ardalis.GuardClauses;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using Wtq.Events;
global using Wtq.Input;
global using Wtq.Utils;