// namespace Wtq.Services.KWin.Input;
//
// public class Qt6KeyName
// {
//
// }
//
// /// <summary>
// /// https://github.com/radekp/qt/blob/master/src/gui/kernel/qkeysequence.cpp.
// /// </summary>
// public class Qt6KeyNames
// {
//     { Qt::Key_Space,        							"Space") },
//     { Qt::Key_Escape,       							"Esc") },
//     { Qt::Key_Tab,          							"Tab") },
//     { Qt::Key_Backtab,      							"Backtab") },
//     { Qt::Key_Backspace,    							"Backspace") },
//     { Qt::Key_Return,       							"Return") },
//     { Qt::Key_Enter,        							"Enter") },
//     { Qt::Key_Insert,       							"Ins") },
//     { Qt::Key_Delete,       							"Del") },
//     { Qt::Key_Pause,        							"Pause") },
//     { Qt::Key_Print,        							"Print") },
//     { Qt::Key_SysReq,       							"SysReq") },
//     { Qt::Key_Home,         							"Home") },
//     { Qt::Key_End,          							"End") },
//     { Qt::Key_Left,         							"Left") },
//     { Qt::Key_Up,           							"Up") },
//     { Qt::Key_Right,        							"Right") },
//     { Qt::Key_Down,         							"Down") },
//     { Qt::Key_PageUp,       							"PgUp") },
//     { Qt::Key_PageDown,     							"PgDown") },
//     { Qt::Key_CapsLock,     							"CapsLock") },
//     { Qt::Key_NumLock,      							"NumLock") },
//     { Qt::Key_ScrollLock,   							"ScrollLock") },
//     { Qt::Key_Menu,         							"Menu") },
//     { Qt::Key_Help,         							"Help") },
//     { Qt::Key_Back,                       				"Back") },
//     { Qt::Key_Forward,                    				"Forward") },
//     { Qt::Key_Stop,                       				"Stop") },
//     { Qt::Key_Refresh,                    				"Refresh") },
//     { Qt::Key_VolumeDown,                 				"Volume Down") },
//     { Qt::Key_VolumeMute,                 				"Volume Mute") },
//     { Qt::Key_VolumeUp,                   				"Volume Up") },
//     { Qt::Key_BassBoost,                  				"Bass Boost") },
//     { Qt::Key_BassUp,                     				"Bass Up") },
//     { Qt::Key_BassDown,                   				"Bass Down") },
//     { Qt::Key_TrebleUp,                   				"Treble Up") },
//     { Qt::Key_TrebleDown,                 				"Treble Down") },
//     { Qt::Key_MediaPlay,                  				"Media Play") },
//     { Qt::Key_MediaStop,                  				"Media Stop") },
//     { Qt::Key_MediaPrevious,              				"Media Previous") },
//     { Qt::Key_MediaNext,                  				"Media Next") },
//     { Qt::Key_MediaRecord,                				"Media Record") },
//     { Qt::Key_HomePage,                   				"Home Page") },
//     { Qt::Key_Favorites,                  				"Favorites") },
//     { Qt::Key_Search,                     				"Search") },
//     { Qt::Key_Standby,                    				"Standby") },
//     { Qt::Key_OpenUrl,                    				"Open URL") },
//     { Qt::Key_LaunchMail,                 				"Launch Mail") },
//     { Qt::Key_LaunchMedia,                				"Launch Media") },
//     { Qt::Key_Launch0,                    				"Launch (0)") },
//     { Qt::Key_Launch1,                    				"Launch (1)") },
//     { Qt::Key_Launch2,                    				"Launch (2)") },
//     { Qt::Key_Launch3,                    				"Launch (3)") },
//     { Qt::Key_Launch4,                    				"Launch (4)") },
//     { Qt::Key_Launch5,                    				"Launch (5)") },
//     { Qt::Key_Launch6,                    				"Launch (6)") },
//     { Qt::Key_Launch7,                    				"Launch (7)") },
//     { Qt::Key_Launch8,                    				"Launch (8)") },
//     { Qt::Key_Launch9,                    				"Launch (9)") },
//     { Qt::Key_LaunchA,                    				"Launch (A)") },
//     { Qt::Key_LaunchB,                    				"Launch (B)") },
//     { Qt::Key_LaunchC,                    				"Launch (C)") },
//     { Qt::Key_LaunchD,                    				"Launch (D)") },
//     { Qt::Key_LaunchE,                    				"Launch (E)") },
//     { Qt::Key_LaunchF,                    				"Launch (F)") },
//     { Qt::Key_MonBrightnessUp,            				"Monitor Brightness Up") },
//     { Qt::Key_MonBrightnessDown,          				"Monitor Brightness Down") },
//     { Qt::Key_KeyboardLightOnOff,         				"Keyboard Light On/Off") },
//     { Qt::Key_KeyboardBrightnessUp,       				"Keyboard Brightness Up") },
//     { Qt::Key_KeyboardBrightnessDown,     				"Keyboard Brightness Down") },
//     { Qt::Key_PowerOff,                   				"Power Off") },
//     { Qt::Key_WakeUp,                     				"Wake Up") },
//     { Qt::Key_Eject,                      				"Eject") },
//     { Qt::Key_ScreenSaver,                				"Screensaver") },
//     { Qt::Key_WWW,                        				"WWW") },
//     { Qt::Key_Sleep,                      				"Sleep") },
//     { Qt::Key_LightBulb,                  				"LightBulb") },
//     { Qt::Key_Shop,                       				"Shop") },
//     { Qt::Key_History,                    				"History") },
//     { Qt::Key_AddFavorite,                				"Add Favorite") },
//     { Qt::Key_HotLinks,                   				"Hot Links") },
//     { Qt::Key_BrightnessAdjust,           				"Adjust Brightness") },
//     { Qt::Key_Finance,                    				"Finance") },
//     { Qt::Key_Community,                  				"Community") },
//     { Qt::Key_AudioRewind,                				"Audio Rewind") },
//     { Qt::Key_BackForward,                				"Back Forward") },
//     { Qt::Key_ApplicationLeft,            				"Application Left") },
//     { Qt::Key_ApplicationRight,           				"Application Right") },
//     { Qt::Key_Book,                       				"Book") },
//     { Qt::Key_CD,                         				"CD") },
//     { Qt::Key_Calculator,                 				"Calculator") },
//     { Qt::Key_Clear,                      				"Clear") },
//     { Qt::Key_ClearGrab,                  				"Clear Grab") },
//     { Qt::Key_Close,                      				"Close") },
//     { Qt::Key_Copy,                       				"Copy") },
//     { Qt::Key_Cut,                        				"Cut") },
//     { Qt::Key_Display,                    				"Display") },
//     { Qt::Key_DOS,                        				"DOS") },
//     { Qt::Key_Documents,                  				"Documents") },
//     { Qt::Key_Excel,                      				"Spreadsheet") },
//     { Qt::Key_Explorer,                   				"Browser") },
//     { Qt::Key_Game,                       				"Game") },
//     { Qt::Key_Go,                         				"Go") },
//     { Qt::Key_iTouch,                     				"iTouch") },
//     { Qt::Key_LogOff,                     				"Logoff") },
//     { Qt::Key_Market,                     				"Market") },
//     { Qt::Key_Meeting,                    				"Meeting") },
//     { Qt::Key_MenuKB,                     				"Keyboard Menu") },
//     { Qt::Key_MenuPB,                     				"Menu PB") },
//     { Qt::Key_MySites,                    				"My Sites") },
//     { Qt::Key_News,                       				"News") },
//     { Qt::Key_OfficeHome,                 				"Home Office") },
//     { Qt::Key_Option,                     				"Option") },
//     { Qt::Key_Paste,                      				"Paste") },
//     { Qt::Key_Phone,                      				"Phone") },
//     { Qt::Key_Reply,                      				"Reply") },
//     { Qt::Key_Reload,                     				"Reload") },
//     { Qt::Key_RotateWindows,              				"Rotate Windows") },
//     { Qt::Key_RotationPB,                 				"Rotation PB") },
//     { Qt::Key_RotationKB,                 				"Rotation KB") },
//     { Qt::Key_Save,                       				"Save") },
//     { Qt::Key_Send,                       				"Send") },
//     { Qt::Key_Spell,                      				"Spellchecker") },
//     { Qt::Key_SplitScreen,                				"Split Screen") },
//     { Qt::Key_Support,                    				"Support") },
//     { Qt::Key_TaskPane,                   				"Task Panel") },
//     { Qt::Key_Terminal,                   				"Terminal") },
//     { Qt::Key_Tools,                      				"Tools") },
//     { Qt::Key_Travel,                     				"Travel") },
//     { Qt::Key_Video,                      				"Video") },
//     { Qt::Key_Word,                       				"Word Processor") },
//     { Qt::Key_Xfer,                       				"XFer") },
//     { Qt::Key_ZoomIn,                     				"Zoom In") },
//     { Qt::Key_ZoomOut,                    				"Zoom Out") },
//     { Qt::Key_Away,                       				"Away") },
//     { Qt::Key_Messenger,                  				"Messenger") },
//     { Qt::Key_WebCam,                     				"WebCam") },
//     { Qt::Key_MailForward,                				"Mail Forward") },
//     { Qt::Key_Pictures,                   				"Pictures") },
//     { Qt::Key_Music,                      				"Music") },
//     { Qt::Key_Battery,                    				"Battery") },
//     { Qt::Key_Bluetooth,                  				"Bluetooth") },
//     { Qt::Key_WLAN,                       				"Wireless") },
//     { Qt::Key_UWB,                        				"Ultra Wide Band") },
//     { Qt::Key_AudioForward,               				"Audio Forward") },
//     { Qt::Key_AudioRepeat,                				"Audio Repeat") },
//     { Qt::Key_AudioRandomPlay,            				"Audio Random Play") },
//     { Qt::Key_Subtitle,                   				"Subtitle") },
//     { Qt::Key_AudioCycleTrack,            				"Audio Cycle Track") },
//     { Qt::Key_Time,                       				"Time") },
//     { Qt::Key_Select,                     				"Select") },
//     { Qt::Key_View,                       				"View") },
//     { Qt::Key_TopMenu,                    				"Top Menu") },
//     { Qt::Key_Suspend,                    				"Suspend") },
//     { Qt::Key_Hibernate,                  				"Hibernate") },
//     { Qt::Key_Yes,          							"Yes") },
//     { Qt::Key_No,           							"No") },
//     { Qt::Key_Context1,     							"Context1") },
//     { Qt::Key_Context2,     							"Context2") },
//     { Qt::Key_Context3,     							"Context3") },
//     { Qt::Key_Context4,     							"Context4") },
//     { Qt::Key_Call,         							"Call") },
//     { Qt::Key_Hangup,       							"Hangup") },
//     { Qt::Key_Flip,         							"Flip") },
//
//
// }