#!/bin/bash

export FLATPAK_BUILD_ROOT="${FLATPAK_BUILD_ROOT:-/tmp/wtq-flatpak}"
export FLATPAK_BUILD_DIR="${FLATPAK_BUILD_ROOT}/build-dir"
export FLATPAK_REPO="${FLATPAK_BUILD_ROOT}/repo"
export FLATPAK_STATE_DIR="${FLATPAK_BUILD_ROOT}/state-dir"

export FLATPAK_APP=nl.flyingpie.wtq
export FLATPAK_APP_YML="$FLATPAK_APP.yml"

echo "FLATPAK_BUILD_ROOT:..$FLATPAK_BUILD_ROOT"
echo "FLATPAK_BUILD_DIR:...$FLATPAK_BUILD_DIR"
echo "FLATPAK_REPO:........$FLATPAK_REPO"
echo "FLATPAK_STATE_DIR:...$FLATPAK_STATE_DIR"
echo "FLATPAK_APP:.........$FLATPAK_APP"
echo "FLATPAK_APP_YML:.....$FLATPAK_APP_YML"