site_name: WTQ - Quake Mode For (Almost) Any App
site_author: flyingpie

docs_dir: 'pages'
site_dir: 'build'

nav:
- WTQ v2: index.md
- WTQ v2 template: index.tpl.md
- WTQ v1: v1.md
- Reporting Issues: reporting-issues.md
- FAQ: faq.md

theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.ico
  features:
    - content.code.copy
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
  font: false
  highlightjs: true
  hljs_languages:
    - bash
    - powershell
  icon:
    repo: fontawesome/brands/github
  logo: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

repo_name: windows-terminal-quake
repo_url: http://github.com/flyingpie/windows-terminal-quake

extra:
  testvar1: 1234

extra_javascript:
  - assets/highlight/highlight.pack.js
  - assets/config.js
extra_css:
  - assets/highlight/styles/vs2015.css
  - assets/styles.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - sane_lists
  - toc:
      toc_depth: 5
      permalink: true

plugins:
  - include-markdown
  - macros:
      include_yaml:
        - wtqsettings.yml