name: continuous

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  windows-latest:
    name: windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v3
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: 'Run: PublishAll'
        run: ./src/build.cmd PublishAll
      - name: 'Publish: win-x64_self-contained.zip'
        uses: actions/upload-artifact@v3
        with:
          name: win-x64_self-contained.zip
          path: _output/artifacts/win-x64_self-contained.zip
      - name: 'Publish: win-x64_framework-dependent.zip'
        uses: actions/upload-artifact@v3
        with:
          name: win-x64_framework-dependent.zip
          path: _output/artifacts/win-x64_framework-dependent.zip
